language: node_js
node_js:
  - "6"
  - "5"
  - "5.1"
addons:
  code_climate:
    repo_token: 99165db6972d3d0625d8e7d2d2f1482e7dddcbcb5d5632685180acb6776960b6
after_success:
  - npm run test:travis
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
